@baseUrl = http://localhost:3000/api


GET {{baseUrl}}/posts


###

# @name addNewPost
POST {{baseUrl}}/posts
Content-Type: application/json

{
    "title": "Yeu vo Chang"
}

###
# @name updatePost
PATCH {{baseUrl}}/posts/2
Content-Type: application/json

{
    "title": "New hihiha"
}

###
# @name removePost
DELETE  {{baseUrl}}/posts/3
Content-Type: application/json
